### ISSUE TITLE
Append Issue

### ISSUE THREAD

**Issue by jashirouprotips** [canchito-dev/bootstrap-password-toggler#1]
Hi, thanks a lot for your script with the data-toggle for bootstrap v4, is awesome. There is only one problem that is the append div, and this doesn't appear wraping the icon div.

Seems like is not in the "input group"...
![screenshot-2018-4-30 bootstrap password toggler demo](https://user-images.githubusercontent.com/29470002/39443469-f4b68310-4c71-11e8-979e-d6328e011321.png)

and this the correct "input-group"
![screenshot-2018-4-30 input group](https://user-images.githubusercontent.com/29470002/39443662-90892be4-4c72-11e8-98e9-03b96f335f75.png)
 
Sorry but my english is to bad to explain.

**Comment by canchito-dev** [comment]
Hi jashirouprotips,

Many thanks for your feedback. Indeed the input-group was not properly built.

Hope you find the solution to this bug satisfactory.

Please pay attention to the modification on how to append/prepend the button. Now you have to set it up by using the words, append/prepend instead of right/left.

If you find any other issue, please feel free to report it.

Regards,
canchito-dev
